[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://kupiyproday.onrender.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
